### ISSUE TITLE
Document thinpool vars.

### ISSUE THREAD

**Issue by Routhinator** [debops/ansible-lvm#17]
Maybe I'm obtuse, however I'm attempting to determine if this playbook supports LVM thinpools, which I use for my Docker volumes.

Most of the settings seem obvious but I'm not sure if/how I can specify a thinpool volume.

I can see there are vars for thinpool settings in the playbook, but not if there is a way to define a volume as a thinpool.

https://github.com/debops/ansible-lvm/blob/master/vars/lvm_config_2.02.98.yml#L490

**Comment by drybjed** [comment]
Not at the moment. The role was written some time ago and since then, [the lvol module got new parameters](https://docs.ansible.com/ansible/lvol_module.html) which I think would allow you to do that. I guess that the role should be updated at some point. For now, you should write your own playbook with the tasks, you can put it in the `ansible/playbooks/` directory relative to the DebOps project directory and run with `debops <playbook-name-without-extension>` command.

**Comment by ganto** [comment]
I don't think you can do thin-pools with the `debops.lvm` module yet. Actually I once wanted to add it, until I figured out, that's still a bit complicated with the Ansible `lvol` module in its current state. Therefore I opened ansible/ansible#19312. Unfortunately, It's not really making a lot of progress.

There would be another way to configure thin-pool volumes as you can see in e.g. https://github.com/ansible/ansible-modules-extras/pull/3042#issuecomment-264667585. If you want to support configurations like this in DebOps, there is still a lot of work needed on this role.

At the moment this is unfortunately not really a priority for me. If you would like to get your hands dirty, I guess every PR would be welcome 😄

**Comment by Routhinator** [comment]
I wonder how dangerous it would be to just create a playbook that calls the `lvconvert` command after the devops.lvm playbook is called... All I really need is to run one command post-create like in the Docker docs:

https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production
